### ISSUE TITLE
Doubled Spine-Models and no Loen in Spine->Char

### ISSUE THREAD

**Issue by Zormolo** [myssal/Brown-Dust-Asset#19]
Some spine models are doubled like
in Spine->char
<img width="140" height="58" alt="Image" src="https://github.com/user-attachments/assets/ab9d990d-c1f9-4f7c-ad86-e37c2f5f4592" />
but the files in char000402-folder have an extra .skel. in all fileNames

all loen costume are in spine->char besides base loen which is in spine->npc folder

**Comment by Zormolo** [comment]
UI->icon->icon_costume

icon_costume101_1.png
icon_costume201_2.png
icon_costume202_3.png
icon_costume301_7.png
icon_costume401_10.png
icon_costume501_13.png
icon_costume601_14.png

dont have the same name convention as all the other files
icon_costumeXXXXXX_number.png like icon_costume000102_21.png

**Comment by Zormolo** [comment]
Spine->cutscenes
Summer nebris cutscene is twice in there
onces as cutscene_char003302 and onces as cutscene_char061303
the first one should be the right one based on the charId

**Comment by myssal** [comment]
Those issues should be fixed by commit 1c6a6358b07a7c2cc732da35a5cc8301075a5dc8

**Comment by Zormolo** [comment]
> Those issues should be fixed by commit [1c6a635](https://github.com/myssal/Brown-Dust-2-Asset/commit/1c6a6358b07a7c2cc732da35a5cc8301075a5dc8)

<img width="105" height="84" alt="Image" src="https://github.com/user-attachments/assets/71593de5-09c0-4493-ac48-274316b65e57" />

base loen is still not in the spine -> char folder aka char003201

and that is still the case too

UI->icon->icon_costume

icon_costume101_1.png
icon_costume201_2.png
icon_costume202_3.png
icon_costume204_15.png
icon_costume301_7.png
icon_costume401_10.png
icon_costume501_13.png
icon_costume601_14.png

dont have the same name convention as all the other files
icon_costumeXXXXXX_number.png like icon_costume000102_21.png

**Comment by Zormolo** [comment]
from what i can tell it looks fine now
still working on checking more but i will close this issue
